[phases.setup]
nixPkgs = ["rust", "cargo", "pkg-config", "openssl", "sqlite"]

[phases.build]
cmds = [
    "cargo build --release",
    "strip target/release/cerberus-bot"
]

[start]
cmd = "./target/release/cerberus-bot"
