[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./target/release/cerberus-bot"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
